services:
  app:
    image: event_system_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
